# Generated by Django 5.0.7 on 2024-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments'),
        ),
    ]
