# Generated by Django 5.0.7 on 2024-07-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmets_code_alter_departmets_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmets',
            name='universal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
