# Generated by Django 5.0.7 on 2024-07-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_departmets_universal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmets',
            name='code',
        ),
        migrations.RemoveField(
            model_name='departmets',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='departmets',
            name='universal_name',
        ),
    ]
