# Generated by Django 5.0.7 on 2024-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_remove_departmets_code_remove_departmets_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmets',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='departmets',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
