# Generated by Django 5.0.7 on 2024-07-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_departmets_code_departmets_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmets',
            name='code',
        ),
        migrations.RemoveField(
            model_name='departmets',
            name='short_name',
        ),
    ]
