# Generated by Django 5.0.7 on 2024-07-17 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_departmets_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('position', models.CharField(max_length=100)),
                ('teacher_image', models.ImageField(upload_to='teachers')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teacherDepartment', to='departments.departmets')),
                ('techer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='teacherProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
