# Generated by Django 5.0.7 on 2024-07-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='techer',
            new_name='teacher',
        ),
    ]
