# Generated by Django 5.0.7 on 2024-07-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherprofile_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='position',
        ),
    ]
