# Generated by Django 5.0.7 on 2024-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacherprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers'),
        ),
    ]
