# Generated by Django 5.0.7 on 2024-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacherprofile_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='routine_img',
            field=models.ImageField(blank=True, null=True, upload_to='routines'),
        ),
    ]
