# Generated by Django 5.0.7 on 2024-07-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmets_code_alter_departmets_name_and_more'),
        ('teachers', '0008_teacherprofile_routine_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teacherDepartment', to='departments.departmets'),
        ),
    ]
