# Generated by Django 5.0.7 on 2024-07-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacherprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
