# Generated by Django 5.0.7 on 2024-07-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0004_alter_collage_image'),
        ('teachers', '0010_teacherprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='collage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherCollage', to='collage.collage'),
        ),
    ]
