# Generated by Django 5.0.7 on 2024-07-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_collage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
