# Generated by Django 5.0.7 on 2024-07-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0003_collage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='image',
            field=models.ImageField(upload_to='collage'),
        ),
    ]
