# Generated by Django 5.0.7 on 2024-07-23 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collages', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teachers')),
                ('hiest_digree', models.CharField(blank=True, max_length=100, null=True)),
                ('versity', models.CharField(blank=True, max_length=100, null=True)),
                ('routine_img', models.ImageField(blank=True, null=True, upload_to='routines')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('collage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherCollage', to='collages.collage')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teacherDepartment', to='departments.departments')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
