# Generated by Django 5.0.7 on 2024-07-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departments_field_departments_slug'),
        ('teachers', '0002_teacherprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacherDepartment', to='departments.departments'),
        ),
    ]
