# Generated by Django 5.0.7 on 2024-07-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
