# Generated by Django 5.0.7 on 2024-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_attendence_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
