# Generated by Django 5.0.7 on 2024-08-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='seasson',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sr_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
