# Generated by Django 5.0.7 on 2024-07-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='collage_image',
            field=models.ImageField(upload_to='collage_image'),
        ),
    ]
