# Generated by Django 5.0.7 on 2024-07-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0002_alter_collage_collage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
