# Generated by Django 5.0.7 on 2024-07-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
