# Generated by Django 5.0.7 on 2024-07-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_shift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shift',
            new_name='StudentShift',
        ),
        migrations.RenameField(
            model_name='studentshift',
            old_name='name',
            new_name='shift',
        ),
    ]
