# Generated by Django 5.0.7 on 2024-07-18 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_remove_departmets_code_remove_departmets_short_name'),
        ('students', '0005_rename_shift_studentshift_and_more'),
        ('subjects', '0003_probidhan_subjects_probidhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sr_no', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('registration', models.IntegerField()),
                ('seasson', models.CharField(max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_department', to='departments.departmets')),
                ('probidhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_probidhan', to='subjects.probidhan')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_semester', to='subjects.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
