# Generated by Django 5.0.7 on 2024-07-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_shift', to='students.studentshift'),
        ),
    ]
